### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by zizther** [creode/magic-login#18]
Hi.
Just wondered if you were looking to support Craft 4 with this plugin?

**Comment by creode-dev** [comment]
Hi,

This is definitely on our radar since we will be looking to upgrade one of our sites that uses this plugin to Craft 4 in the future. It is on our list and I'll drop you any updates when work commences.

Thanks

**Comment by zizther** [comment]
@creode-dev Appreciate the update. We are looking to use this on a Craft 4 project, if you need a hand testing let me know.

**Comment by jaymeh** [comment]
@zizther Thanks for offering to test this. I have some good news, the 3.x branch now has support for Craft 4. If you'd like to give it a quick test and generally share any feedback, let us know.

We have a few small things to tidy up and check over from a documentation side before we draft a full release but hoping to get it out soon.

Thanks

**Comment by jaymeh** [comment]
A new version of the plugin has been released for Craft 4.

Thanks
