### ISSUE TITLE
Improvements for Settings section in CP

### ISSUE THREAD

**Issue by zizther** [creode/magic-login#19]
There is no clear way to access the settings in the CP, it would be good to add this to the `Plugins` section within the `Settings` page where the plugin will show in the list of plugin with settings to manage.
Additionally the settings button can be added to the plugin in the Plugins list within the CP.

When you are within the plugin settings section in the CP, it would be good to disable any fields which are being overridden by the `magic-login.php` config file. Additionally you can also show a message to show it is being overridden similar to this example:
<img width="579" alt="Screenshot 2022-12-16 at 02 05 49" src="https://user-images.githubusercontent.com/1436378/208005483-797c2d6d-6101-4a50-b90d-d9e1091a4f66.png">

**Comment by jaymeh** [comment]
Thanks @zizther I'll review this when I get a bit of time (hopefully next week).

**Comment by liam-spedding** [comment]
Hi @zizther, we have added the feature requested above and have created a new release 4.1.0 from this PR 
 #34 

I will now mark this issue as closed.

Thank you
