### ISSUE TITLE
Craft 5 compatibility

### ISSUE THREAD

**Issue by michaeldavidtodd** [creode/magic-login#30]
Are there plans for Craft 5 compatibility? Definitely leaning on this plugin and would love to upgrade.

**Comment by jaymeh** [comment]
@michaeldavidtodd I'll try and get this into the schedule this week.

**Comment by creode-dev** [comment]
@michaeldavidtodd Version 4.0.0 of the plugin has been released. This adds support for Craft 5.

Thanks
