### ISSUE TITLE
Option to automatically log user in after registration

### ISSUE THREAD

**Issue by d-karstens** [creode/magic-login#37]
Hi,

Would it be possible to add an option to log a user in automatically after registration without requiring an email link?

We're setting up a registration/checkout flow where we'd rather register and log a user in behind the scenes early in the flow, rather than block the user by sending them to check their email to log in and then return to continue the checkout

I've tried to work around it by using Craft's `autoLoginAfterAccountActivation` setting, which logs the user in, but the plugin throws this error 

![Screenshot 2024-07-23 at 11-30-13 400 Bad Request](https://github.com/user-attachments/assets/2a2507ea-f2b9-40a7-8144-d387f1093a7a)

Thanks!

**Comment by jaymeh** [comment]
Thanks for flagging this @d-karstens ,

I'll review the above, try to replicate it and get back to you as soon as I can.

**Comment by jaymeh** [comment]
@d-karstens , I've pushed an update to the plugin (v4.3.0) which should address the issue. Managed to get the above like you mentioned and tracked it down to us running the login flow if a user had already logged in via the registration process.

I've put a check in there to try and address this but let me know if you encounter any issues.

Thanks

**Comment by d-karstens** [comment]
Thanks for the fix! It appears to be working for us now
